##定义对象/ map集合
#
#user:
#  name: 张三
#  age: 18
#  sex: 男
#
#  #定义数组/List/set集合
#hobby:
#  - Java
#  - Game
#  - Snowboarding


spring:
  application:
    name: MybatisDemo

  #数据库链接
  datasource:
    type: org.springframework.jdbc.datasource.DelegatingDataSource
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234


#配置mybatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml